services:
  ansible:
    # user: "${UID}:${GID}"
    image: alpine/ansible:latest
    secrets:
      - user_ssh_key
    volumes:
      - .:/work
      - ./.ansible:/root/.ansible
      - ./.ssh:/root/.ssh
    extra_hosts:
      - "server0.local:192.168.98.189"
secrets:
  user_ssh_key:
    file: ~/.ssh/id_ed25519


