##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: server0
ansible_nas_timezone: Etc/UTC

## Enable some applications
heimdall_enabled: true
portainer_enabled: true
glances_enabled: false
# Will be added to the docker group to give user command line access to docker
ansible_nas_user: monty

# Your email and domain, used for Let's Encrypt SSL certs
ansible_nas_email: monty@codetransform.com

# Where you want Docker to store its container data.
docker_home: /mnt/disk1/docker

# Backup & Restore
timemachine_enabled: true
timemachine_password: timemachine
timemachine_share_name: Backup

# samba options
samba_shares_root: /mnt/disk3/resilio/sync
samba_apple_extensions: true
samba_global_include: samba-global-include.conf

# nfs options
nfs_shares_root: /mnt/disk2/nfs
nfs_exports:
  - "{{ nfs_shares_root }}/public *(rw,sync,no_root_squash)"

# plex
plex_enabled: true
plex_hostname: "server0"

youtubedlmaterial_enabled: true
youtubedlmaterial_dl_audio_directory: "{{ plex_tv_directory }}/youtube/audio"
youtubedlmaterial_dl_video_directory: "{{ plex_tv_directory }}/youtube/video"
youtubedlmaterial_dl_subscriptions_directory: "{{ plex_tv_directory }}/youtube/subscriptions"

virtual_desktop_enabled: false
guacamole_enabled: false

resilio_enabled: true
resilio_data_directory: /mnt/disk3/resilio/sync

## openssh
openssh_enabled: true
openssh_data_directory: "/mnt/disk3/"
openssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKAEof1VUD1hzvK6u6SC3/oKFqMyGKCVSiA1SXnx8RQn monty@potteryphotos.local"

###
### MiniDLNA
###
minidlna_enabled: false
minidlna_port: "8200"

